services:
  predictionaccountabilityproject:
    image: predictionaccountabilityproject
    build:
      context: 1.1
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
